config/routes.rb
Rails.application.routes.draw do
	root 'users#logon'
	post 'users/login' => 'users#login'
	resources :users, :only => [:new, :show, :create, :edit, :destroy] do
		resources :conversations, :only => [:index, :show, :new, :create, :destroy] do
			resources :messages, :only => [:create]
		end
	end
	mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :user
	has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
	has_one :conversation
end

app/models/user.rb
class User < ApplicationRecord
	has_many :conversations
	has_many :messages, through: :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def readURI(section)
		uri = request.original_url
		uri.gsub!(/http:\W\W|https:\W\W/i, "")
		uri = uri.split(/\//i)
		return uri[section]
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def show
		@user = User.find_by(id: readURI(2))
		@conversation = Conversation.find_by({user_id: @user.id, id: readURI(4)})
		@message = Message.new
	end

	def index
		@user = User.find_by(id: readURI(2))
		@conversations = Conversation.all
		@conversation = Conversation.new()
	end

	def new
		@conversation = Conversation.new()
	end
	def create
		@conversation = Conversation.new(conversation_params)
		if @conversation.save!
			puts "CONVERSATION CREATED"
		else
			redirect_to(new_user_conversation_url)
		end
	end

	private

	def conversation_params
		params.require(:conversation).permit(:recipients)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create
		@message = Message.new(message_params)
		if @msesage.save!
			puts "MESSAGE CREATED"
			ApplicationCable.server.broadcast 'conversation_channel',
				message: @message.content
		else
			flash[:error] = "The message couldn't be created"
		end
	end

	private

	def message_params
		params.require(:message).permit(:content)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	current_user = nil

	def logon
		@user = User.new()
	end

	def login
		@user = User.new(login_params)
		if @user = User.find_by(user_name: @user.user_name)
			redirect_to(user_conversations_url({user_id: @user.id}))
		else
			puts "CLIENT REDIRECTED"
			redirect_to(root_url)
		end
	end

	def new
		@user = User.new()
	end

	def create
		@user = User.new(signup_params)
		if @user.save!
			redirect_to( user_url({id: @user}), :notice => "Sie haben sich erfolgreich angemeldet!" )
		else
			redirect_to(new_user_url)
		end
	end

	def show
		@user = User.find_by(id: readURI(2))
	end

	private

	def signup_params
		params.require(:user).permit(:user_name, :password, :first_name, :last_name)
	end

	def login_params
		params.require(:user).permit(:user_name, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/index.html.erb
<h1>Das sine Sie Gespräche</h1>
<ul>

<% @user.conversations.each do |c| %>
	<pre>Empfänger: <% c.recipients.split(/\s/i).map { |usr| usr = User.find_by(id: usr).first_name }.each do |usr| %> <%= usr %> <% end %> Erstellt bei: <%= c.created_at %> <%= link_to("Gehe zu Konversation", user_conversation_url({user_id: @user.id, id: c.id})) %></pre>
<% end %>

<%= form_for [:user, @conversation] do |fields| %>
	<%= fields.text_field(:recipients) %>
	<%= submit_tag('Konversation erstellen') %>
<% end %>

</ul>

app/views/conversations/show.html.erb
<pre>Du bist: <%= @user.first_name %></pre>
<pre>Gespräch mit:<% @conversation.recipients.split(/\s/i).map { |usr| usr = User.find_by(id: usr).first_name }.each do |usr| %> <%= usr %><% end %></pre>

<% @conversation.messages.each do |msg| %>
	<%= msg.content %><br>
<% end %>

<%= form_for [:user, :conversation, @message] do |fields| %>
	<%= fields.text_field :content %>
	<%= submit_tag 'Send' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Messenger</title>
		<%= csrf_meta_tags %>
		<%= action_cable_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= yield %>
	</body>
</html>

app/views/users/logon.html.erb
<h1>Einloggen oder Anmeldung für Material messenger</h1>
<%= form_for @user, url: { action: "login" } do |fields| %>
	<%= fields.text_field( :user_name ) %> <br>
	<%= password_field(:login, :password) %> <br>
	<%= submit_tag( 'login' )  %>
<% end %>
<%= link_to('Haben Sie kein Konto? Jetzt Anmelden!', new_user_url) %>

app/views/users/new.html.erb
<h1>Ein Konto erstellen!</h1>
<%= form_for @user, url: { action: 'create' } do |fields| %>
	<p> Fn <%= fields.text_field( :first_name ) %> </p> <br>
	<p> Ln <%= fields.text_field( :last_name ) %> </p> <br>
	<p> Name <%= fields.text_field( :user_name ) %> </p> <br>
	<p> Passwort: <%= password_field(:create, :password) %> </p> <br>
	<%= submit_tag( 'create' ) %>
<% end %>

app/views/users/show.html.erb
<h1>Das sine Sie Gespräche</h1>
<ul>

<% @user.conversations.each do |c| %>
	<pre>Empfänger: <%= c.recipients %> Erstellt bei <%= c.created_at %> </pre>
<% end %>

</ul>